# Build a manifest for course datasets and simulated analogs.

required_packages <- c("dplyr", "readr", "stringr")
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]

if (length(missing_packages) > 0) {
  stop(
    "Install required packages before running this script: ",
    paste(missing_packages, collapse = ", "),
    call. = FALSE
  )
}

library(dplyr)
library(readr)
library(stringr)

manifest_path <- "data/manifest.csv"
crosswalk_path <- "data/simulated/simulated_dataset_crosswalk.csv"
codebook_dir <- "data/codebooks"

dir.create(codebook_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(crosswalk_path)) {
  stop("Could not find simulated dataset crosswalk: ", crosswalk_path, call. = FALSE)
}

dataset_shape <- function(path) {
  data <- read_csv(path, show_col_types = FALSE)
  tibble(n_rows = nrow(data), n_columns = ncol(data))
}

dataset_id <- function(path) {
  str_remove(basename(path), "\\.csv$")
}

real_codebook <- function(path) {
  file.path(codebook_dir, paste0(dataset_id(path), ".md"))
}

simulated_codebook <- function(path) {
  file.path(codebook_dir, paste0("simulated_", dataset_id(path), ".md"))
}

crosswalk <- read_csv(crosswalk_path, show_col_types = FALSE) |>
  mutate(analog_pair_id = row_number())

real_rows <- crosswalk |>
  transmute(
    dataset_id = dataset_id(real_file),
    file_path = real_file,
    dataset_kind = "real",
    analog_pair_id,
    analog_topic,
    paired_dataset_path = simulated_file,
    codebook_path = real_codebook(real_file)
  )

simulated_rows <- crosswalk |>
  transmute(
    dataset_id = dataset_id(simulated_file),
    file_path = simulated_file,
    dataset_kind = "simulated",
    analog_pair_id,
    analog_topic,
    paired_dataset_path = real_file,
    codebook_path = simulated_codebook(simulated_file)
  )

metadata_rows <- tibble(
  dataset_id = c("simulated_dataset_crosswalk", "data_manifest"),
  file_path = c(crosswalk_path, manifest_path),
  dataset_kind = "metadata",
  analog_pair_id = NA_integer_,
  analog_topic = c("real-to-simulated dataset crosswalk", "data directory manifest"),
  paired_dataset_path = NA_character_,
  codebook_path = file.path(codebook_dir, c("simulated_dataset_crosswalk.md", "data_manifest.md"))
)

manifest_without_shapes <- bind_rows(real_rows, simulated_rows, metadata_rows) |>
  arrange(dataset_kind, analog_pair_id, dataset_id)

shape_rows <- lapply(manifest_without_shapes$file_path, function(path) {
  if (path == manifest_path) {
    tibble(n_rows = nrow(manifest_without_shapes), n_columns = ncol(manifest_without_shapes) + 2)
  } else {
    dataset_shape(path)
  }
}) |>
  bind_rows()

manifest <- bind_cols(manifest_without_shapes, shape_rows) |>
  select(
    dataset_id,
    dataset_kind,
    file_path,
    codebook_path,
    n_rows,
    n_columns,
    analog_pair_id,
    analog_topic,
    paired_dataset_path
  )

writeLines(
  c(
    "# Simulated Dataset Crosswalk",
    "",
    "Source: generated by `scripts/simulate-teaching-data.R`.",
    "",
    "Unit of observation: one real-to-simulated dataset pairing.",
    "",
    "## Variables",
    "",
    "- `real_file`: path to the real teaching dataset.",
    "- `simulated_file`: path to the simulated analog dataset with matching column names.",
    "- `analog_topic`: short description of the simulated analog topic."
  ),
  file.path(codebook_dir, "simulated_dataset_crosswalk.md")
)

writeLines(
  c(
    "# Data Manifest",
    "",
    "Source: generated by `scripts/build-data-manifest.R`.",
    "",
    "Unit of observation: one CSV file in the course data inventory.",
    "",
    "## Variables",
    "",
    "- `dataset_id`: filename without `.csv`.",
    "- `dataset_kind`: `real`, `simulated`, or `metadata`.",
    "- `file_path`: path to the CSV file.",
    "- `codebook_path`: path to the matching codebook.",
    "- `n_rows`: number of rows in the CSV.",
    "- `n_columns`: number of columns in the CSV.",
    "- `analog_pair_id`: identifier linking real datasets to their simulated analogs; missing for metadata files.",
    "- `analog_topic`: short description of the pairing or metadata file.",
    "- `paired_dataset_path`: path to the paired real or simulated file; missing for metadata files."
  ),
  file.path(codebook_dir, "data_manifest.md")
)

missing_codebooks <- manifest$codebook_path[!file.exists(manifest$codebook_path)]

if (length(missing_codebooks) > 0) {
  stop(
    "Missing codebooks for manifest entries: ",
    paste(missing_codebooks, collapse = ", "),
    call. = FALSE
  )
}

write_csv(manifest, manifest_path, na = "")
message("Wrote ", manifest_path, " (", nrow(manifest), " rows, ", ncol(manifest), " columns)")
message("Wrote metadata codebooks in ", codebook_dir)
