# Simulate swappable cousin datasets for course teaching data.
#
# Files are written to data/simulated/ with the same basenames and column names
# as selected real files in data/real/. This makes it easy to swap real and
# simulated examples by changing only the directory in a path.

required_packages <- c("dplyr", "readr", "stringr", "tidyr")
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]

if (length(missing_packages) > 0) {
  stop(
    "Install required packages before running this script: ",
    paste(missing_packages, collapse = ", "),
    call. = FALSE
  )
}

library(dplyr)
library(readr)
library(stringr)
library(tidyr)

set.seed(20260604)

output_dir <- "data/simulated"
codebook_dir <- "data/codebooks"

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(codebook_dir, recursive = TRUE, showWarnings = FALSE)

write_sim_csv <- function(data, filename) {
  path <- file.path(output_dir, filename)
  write_csv(data, path, na = "")
  message("Wrote ", path, " (", nrow(data), " rows, ", ncol(data), " columns)")
}

write_sim_codebook <- function(filename, real_file, topic, unit, notes) {
  path <- file.path(codebook_dir, filename)
  writeLines(
    c(
      paste0("# Simulated ", str_remove(filename, "\\.md$")),
      "",
      "Source: simulated teaching data generated by `scripts/simulate-teaching-data.R`.",
      "",
      paste0("Designed as a swappable cousin for `", real_file, "`."),
      "",
      paste0("Topic: ", topic),
      "",
      paste0("Unit of observation: ", unit),
      "",
      "Important caution: these data are fully simulated. They should be used for teaching, practice, and demonstrations only.",
      "",
      "Notes:",
      "",
      paste0("- ", notes)
    ),
    path
  )
  message("Wrote ", path)
}

sample_cat <- function(values, n, prob = NULL) {
  sample(values, n, replace = TRUE, prob = prob)
}

bounded_normal <- function(n, mean, sd, lower = -Inf, upper = Inf) {
  pmin(pmax(rnorm(n, mean, sd), lower), upper)
}

missing_some <- function(x, prop) {
  idx <- sample(seq_along(x), size = floor(length(x) * prop))
  x[idx] <- NA
  x
}

logit <- function(x) 1 / (1 + exp(-x))

food_source_label <- function(x) {
  case_when(
    x == 1 ~ "Store grocery/supermarket",
    x == 2 ~ "Restaurant with waiter/waitress",
    x == 3 ~ "Restaurant fast food/Pizza",
    x == 4 ~ "Bar/Tavern/Lounge",
    x == 5 ~ "Restaurant, no additional information",
    x == 6 ~ "Cafeteria not in a K-12 school",
    x == 7 ~ "Cafeteria in a K-12 school",
    x == 8 ~ "Child/Adult care center",
    x == 9 ~ "Child/Adult home care",
    x == 10 ~ "Soup kitchen/shelter/food pantry facility",
    x == 11 ~ "Meals on Wheels Program",
    x == 12 ~ "Community food program - other",
    x == 13 ~ "Community program, no additional info",
    x == 14 ~ "Vending machine",
    x == 15 ~ "Common coffee pot or snack tray",
    x == 16 ~ "From someone else/gift",
    x == 17 ~ "Mail order purchase",
    x == 18 ~ "Residential dining facility",
    x == 19 ~ "Grown or caught by you or someone you know",
    x == 20 ~ "Fish caught by you or someone you know",
    x == 24 ~ "Sport, recreation, or entertainment",
    x == 25 ~ "Street vendor, vending truck",
    x == 26 ~ "Fundraiser sales",
    x == 27 ~ "Store - convenience type",
    x == 28 ~ "Store - no additional information",
    x == 91 ~ "Other",
    TRUE ~ NA_character_
  )
}

food_source_group <- function(x) {
  case_when(
    x %in% c(1, 27, 28) ~ "store",
    x %in% c(2, 3, 4, 5, 25) ~ "restaurant_or_vendor",
    x %in% c(6, 7, 8, 9, 18) ~ "institutional_or_care_setting",
    x %in% c(10, 11, 12, 13) ~ "community_food_program",
    x %in% c(14, 15, 17, 24, 26, 91) ~ "other_purchased_or_other",
    x %in% c(16, 19, 20) ~ "gift_or_homegrown",
    TRUE ~ NA_character_
  )
}

# Davis-style measured/reported height and weight ------------------------------

n_davis <- 220
davis_sex <- sample_cat(c("female", "male"), n_davis, c(0.55, 0.45))
davis_height <- if_else(
  davis_sex == "female",
  bounded_normal(n_davis, 164, 7, 145, 188),
  bounded_normal(n_davis, 177, 8, 155, 205)
)
davis_bmi <- if_else(
  davis_sex == "female",
  bounded_normal(n_davis, 24.5, 4.8, 16, 46),
  bounded_normal(n_davis, 26.0, 5.2, 17, 48)
)
davis_weight <- davis_bmi * (davis_height / 100)^2
davis_reported_weight <- davis_weight + if_else(davis_sex == "female", rnorm(n_davis, -1.8, 3.2), rnorm(n_davis, 0.8, 3.8))
davis_reported_height <- davis_height + if_else(davis_sex == "female", rnorm(n_davis, -1.5, 2.2), rnorm(n_davis, -2.0, 2.8))
davis_reported_weight <- missing_some(round(davis_reported_weight), 0.08)
davis_reported_height <- missing_some(round(davis_reported_height), 0.08)
davis_weight[12] <- 158
davis_height[12] <- 58

davis_height_weight <- tibble(
  participant_id = seq_len(n_davis),
  sex = davis_sex,
  weight_kg = round(davis_weight),
  height_cm = round(davis_height),
  reported_weight_kg = davis_reported_weight,
  reported_height_cm = davis_reported_height
) |>
  mutate(
    measured_bmi = weight_kg / (height_cm / 100)^2,
    reported_bmi = reported_weight_kg / (reported_height_cm / 100)^2,
    weight_reporting_error_kg = reported_weight_kg - weight_kg,
    height_reporting_error_cm = reported_height_cm - height_cm,
    missing_reported_weight = is.na(reported_weight_kg),
    missing_reported_height = is.na(reported_height_cm),
    likely_swapped_measured_values = weight_kg > 120 & height_cm < 100
  )

write_sim_csv(davis_height_weight, "measured_vs_self_reported_exercise_minutes.csv")
write_sim_codebook("simulated_measured_vs_self_reported_exercise_minutes.md", "data/real/davis_height_weight.csv", "measured and self-reported exercise minutes", "one person", "Uses the same columns as the height/weight dataset, but frames the records as a measurement-error exercise-minute study.")

# Migraine-style headache diary ------------------------------------------------

n_migraine_people <- 140
migraine_people <- tibble(
  participant_id = seq_len(n_migraine_people),
  medication = sample_cat(c("continuing", "reduced", "none"), n_migraine_people, c(0.45, 0.30, 0.25)),
  baseline_risk = rnorm(n_migraine_people, 0, 0.9)
)

migraine_headache_diary <- migraine_people |>
  rowwise() |>
  do({
    days <- sort(sample(-20:90, sample(18:80, 1)))
    tibble(participant_id = .$participant_id, day = days, medication = .$medication, baseline_risk = .$baseline_risk)
  }) |>
  ungroup() |>
  mutate(
    medication_effect = case_when(
      medication == "continuing" ~ 0.55,
      medication == "reduced" ~ 0.25,
      TRUE ~ -0.25
    ),
    time_effect = -0.006 * pmax(day, 0),
    headache_probability = logit(-0.15 + baseline_risk + medication_effect + time_effect),
    headache_reported = runif(n()) < headache_probability,
    headache = if_else(headache_reported, "yes", "no")
  ) |>
  select(participant_id, day, medication, headache, headache_reported) |>
  arrange(participant_id, day)

write_sim_csv(migraine_headache_diary, "toothache_diary.csv")
write_sim_codebook("simulated_toothache_diary.md", "data/real/migraine_headache_diary.csv", "toothache diary with care-advice groups", "one person-day", "Includes unequal diary lengths, negative pre-reference days, treatment/advice groups, and changing toothache probabilities over time.")

# Titanic-style passenger survival --------------------------------------------

n_titanic <- 1250
titanic_class <- sample_cat(c("1st", "2nd", "3rd"), n_titanic, c(0.25, 0.22, 0.53))
titanic_sex <- sample_cat(c("female", "male"), n_titanic, c(0.38, 0.62))
titanic_age <- pmax(0, round(rlnorm(n_titanic, log(28), 0.55), 1))
titanic_age[sample(seq_len(n_titanic), floor(0.48 * n_titanic))] <- NA
titanic_survival_p <- logit(
  -1.4 +
    if_else(titanic_sex == "female", 1.7, 0) +
    case_when(titanic_class == "1st" ~ 1.0, titanic_class == "2nd" ~ 0.35, TRUE ~ -0.15) +
    if_else(!is.na(titanic_age) & titanic_age < 12, 0.55, 0)
)

titanic_passengers <- tibble(
  passenger_name = paste0("Passenger ", str_pad(seq_len(n_titanic), 4, pad = "0")),
  survived_logical = runif(n_titanic) < titanic_survival_p,
  survived = if_else(survived_logical, "yes", "no"),
  age_years = titanic_age,
  passenger_class = titanic_class,
  sex = titanic_sex,
  missing_age = is.na(age_years)
) |>
  select(passenger_name, survived, age_years, passenger_class, sex, survived_logical, missing_age)

write_sim_csv(titanic_passengers, "boaty_mcboatface_passengers.csv")
write_sim_codebook("simulated_boaty_mcboatface_passengers.md", "data/real/titanic_passengers.csv", "fictional passenger survival by class, sex, and age", "one passenger", "Includes missing ages and class/sex survival differences for categorical comparison practice.")

# Infant mortality-style country indicators -----------------------------------

n_countries <- 110
regions <- sample_cat(c("Africa", "Americas", "Asia", "Europe"), n_countries, c(0.28, 0.24, 0.30, 0.18))
income <- case_when(
  regions == "Africa" ~ rlnorm(n_countries, log(900), 0.8),
  regions == "Asia" ~ rlnorm(n_countries, log(2200), 0.9),
  regions == "Americas" ~ rlnorm(n_countries, log(4500), 0.8),
  TRUE ~ rlnorm(n_countries, log(8500), 0.45)
)
oil_exporter <- runif(n_countries) < case_when(regions == "Asia" ~ 0.18, regions == "Africa" ~ 0.15, TRUE ~ 0.05)
infant_rate <- 145 - 16 * log(pmax(income, 200)) + if_else(oil_exporter, 10, 0) + rnorm(n_countries, 0, 10)

infant_mortality_countries <- tibble(
  country_name = paste0("Country ", str_pad(seq_len(n_countries), 3, pad = "0")),
  income_usd_per_capita = round(income),
  infant_mortality_per_1000 = round(pmax(infant_rate, 3), 1),
  region = regions,
  oil_exporting_country = if_else(oil_exporter, "yes", "no"),
  oil_exporter = oil_exporter
) |>
  arrange(region, country_name)

write_sim_csv(infant_mortality_countries, "rural_health_indicators.csv")
write_sim_codebook("simulated_rural_health_indicators.md", "data/real/infant_mortality_countries.csv", "rural health indicators by region and income", "one area/country-like unit", "Includes a nonlinear income-health association, regional clustering, and a small resource-exporter effect.")

# Depression-scale style measures ---------------------------------------------

n_depression <- 95
latent_distress <- rnorm(n_depression)
simplicity <- pmax(0, pmin(2.2, 0.8 + 0.35 * latent_distress + rnorm(n_depression, 0, 0.25)))
fatalism <- pmax(-0.6, pmin(2.3, 0.55 + 0.55 * latent_distress + rnorm(n_depression, 0, 0.35)))
depression <- pmax(0, pmin(2.2, 0.65 + 0.42 * simplicity + 0.30 * fatalism + rnorm(n_depression, 0, 0.22)))

ginzberg_depression <- tibble(
  participant_id = seq_len(n_depression),
  simplicity = round(simplicity, 5),
  fatalism = round(fatalism, 5),
  depression = round(depression, 5),
  adjsimplicity = round(residuals(lm(simplicity ~ fatalism)) + mean(simplicity), 5),
  adjfatalism = round(residuals(lm(fatalism ~ simplicity)) + mean(fatalism), 5),
  adjdepression = round(residuals(lm(depression ~ simplicity + fatalism)) + mean(depression), 5)
)

write_sim_csv(ginzberg_depression, "stress_beliefs_survey.csv")
write_sim_codebook("simulated_stress_beliefs_survey.md", "data/real/ginzberg_depression.csv", "stress, outlook, and mood-related scales", "one subject", "Includes correlated scale variables and adjusted residual-style versions for association examples.")

# Exercise/eating-disorder repeated observations -------------------------------

n_exercise_subjects <- 210
exercise_subjects <- tibble(
  subject_id = as.character(seq_len(n_exercise_subjects)),
  group = sample_cat(c("control", "patient"), n_exercise_subjects, c(0.42, 0.58)),
  random_intercept = rnorm(n_exercise_subjects, 0, 1.1)
)

exercise_eating_disorders <- exercise_subjects |>
  rowwise() |>
  do({
    ages <- sort(sample(c(8, 10, 12, 14, 16, 17.5), sample(3:5, 1)))
    tibble(subject_id = .$subject_id, group = .$group, age_years = ages, random_intercept = .$random_intercept)
  }) |>
  ungroup() |>
  mutate(
    expected = if_else(group == "patient", 1.2 + 0.42 * (age_years - 8), 1.6 + 0.08 * (age_years - 8)) + random_intercept,
    exercise_hours_per_week = pmax(0, round(rlnorm(n(), log(pmax(expected, 0.2)), 0.55), 2))
  ) |>
  select(subject_id, age_years, exercise_hours_per_week, group) |>
  arrange(group, subject_id, age_years)

write_sim_csv(exercise_eating_disorders, "physical_therapy_activity.csv")
write_sim_codebook("simulated_physical_therapy_activity.md", "data/real/exercise_eating_disorders.csv", "physical therapy activity histories by group", "one subject-age observation", "Includes repeated age observations, skewed activity hours, and group-specific trajectories.")

# Post-coma recovery-style data ------------------------------------------------

n_coma <- 330
coma_duration <- pmax(1, round(rlnorm(n_coma, log(6), 0.75)))
days_post <- pmax(1, round(rlnorm(n_coma, log(28), 0.55)))
coma_age <- bounded_normal(n_coma, 39, 18, 16, 82)
coma_sex <- sample_cat(c("female", "male"), n_coma, c(0.42, 0.58))
recovery_score <- 93 + 0.18 * days_post - 0.9 * coma_duration - 0.10 * (coma_age - 40) + rnorm(n_coma, 0, 13)

post_coma_recovery <- tibble(
  patient_id = 5000 + seq_len(n_coma),
  days_post_coma = days_post,
  coma_duration_days = coma_duration,
  sex = coma_sex,
  age_at_injury_years = round(coma_age, 5),
  performance_iq = round(pmax(40, pmin(145, recovery_score + rnorm(n_coma, -3, 8)))),
  verbal_iq = round(pmax(40, pmin(145, recovery_score + rnorm(n_coma, 2, 9))))
) |>
  arrange(patient_id)

write_sim_csv(post_coma_recovery, "injury_recovery_followup.csv")
write_sim_codebook("simulated_injury_recovery_followup.md", "data/real/post_coma_recovery.csv", "injury recovery follow-up scores", "one patient follow-up measurement", "Includes recovery timing, injury duration, age, sex, and correlated performance/verbal score outcomes.")

# NHANES-style demographics ----------------------------------------------------

n_nhanes <- 6000
respondent_ids <- 900001:(900000 + n_nhanes)
age_years <- sample(0:80, n_nhanes, replace = TRUE, prob = dpois(0:80, 35) + 0.01)
gender <- sample_cat(c("female", "male"), n_nhanes, c(0.52, 0.48))
race_ethnicity <- sample_cat(
  c("Mexican American", "Other Hispanic", "Non-Hispanic White", "Non-Hispanic Black", "Non-Hispanic Asian", "Other race including multiracial"),
  n_nhanes,
  c(0.10, 0.12, 0.52, 0.14, 0.06, 0.06)
)
examined <- runif(n_nhanes) < plogis(1.6 - 0.006 * abs(age_years - 45))
born_in_us <- sample_cat(c("yes", "no"), n_nhanes, c(0.84, 0.16))
education <- rep(NA_character_, n_nhanes)
adult_idx <- age_years >= 20
education[adult_idx] <- sample_cat(
  c("Less than 9th grade", "9-11th grade", "High school/GED", "Some college/AA", "College graduate or above"),
  sum(adult_idx),
  c(0.06, 0.10, 0.23, 0.32, 0.29)
)
marital <- rep(NA_character_, n_nhanes)
marital[adult_idx] <- sample_cat(c("Married/living with partner", "Widowed/divorced/separated", "Never married"), sum(adult_idx), c(0.52, 0.25, 0.23))
income_poverty <- pmin(5, pmax(0, rgamma(n_nhanes, 2.2, 0.75)))
income_poverty <- missing_some(round(income_poverty, 2), 0.15)

nhanes_2021_2023_demographics <- tibble(
  respondent_id = respondent_ids,
  release_cycle = 12,
  interview_exam_status = if_else(examined, "interviewed_and_examined", "interviewed_only"),
  gender,
  age_years,
  age_months_screening_0_to_24 = if_else(age_years <= 2, as.numeric(sample(0:24, n_nhanes, replace = TRUE)), NA_real_),
  age_group = case_when(age_years < 18 ~ "0-17", age_years < 30 ~ "18-29", age_years < 45 ~ "30-44", age_years < 65 ~ "45-64", age_years < 80 ~ "65-79", TRUE ~ "80+"),
  race_ethnicity,
  exam_period = if_else(examined, sample_cat(c("November-April", "May-October"), n_nhanes), NA_character_),
  born_in_us,
  years_in_us_category = if_else(born_in_us == "no", sample_cat(c("Less than 1 year", "1-4 years", "5-9 years", "10-14 years", "15-19 years", "20 years or more"), n_nhanes, c(0.05, 0.12, 0.16, 0.18, 0.15, 0.34)), NA_character_),
  education_adults_20_plus = education,
  marital_status_adults_20_plus = marital,
  pregnancy_status_exam = if_else(gender == "female" & age_years >= 20 & age_years <= 44 & examined, sample_cat(c("pregnant", "not_pregnant", "cannot_ascertain"), n_nhanes, c(0.035, 0.76, 0.205)), NA_character_),
  household_size = sample(1:7, n_nhanes, replace = TRUE, prob = c(0.17, 0.27, 0.20, 0.15, 0.10, 0.06, 0.05)),
  family_income_to_poverty = income_poverty,
  interview_weight = round(runif(n_nhanes, 4500, 180000), 6),
  mec_exam_weight = if_else(examined, round(runif(n_nhanes, 4500, 230000), 6), 0),
  masked_variance_stratum = sample(173:187, n_nhanes, replace = TRUE),
  masked_variance_psu = sample(1:2, n_nhanes, replace = TRUE)
)

write_sim_csv(nhanes_2021_2023_demographics, "neighborhood_health_survey_demographics.csv")
write_sim_codebook("simulated_neighborhood_health_survey_demographics.md", "data/real/nhanes_2021_2023_demographics.csv", "neighborhood health survey demographics", "one participant", "Includes age, gender, race/ethnicity, education, income-to-poverty, household size, weights, and design-like variables.")

# NHANES-style blood pressure --------------------------------------------------

bp_eligible <- nhanes_2021_2023_demographics |>
  filter(age_years >= 8, interview_exam_status == "interviewed_and_examined") |>
  sample_n(min(n(), 3900))

bp_base <- 101 + 0.55 * bp_eligible$age_years + if_else(bp_eligible$gender == "male", 4, 0) + rnorm(nrow(bp_eligible), 0, 12)
di_base <- 62 + 0.20 * bp_eligible$age_years + if_else(bp_eligible$gender == "male", 2, 0) + rnorm(nrow(bp_eligible), 0, 8)
pulse_base <- 77 - 0.05 * bp_eligible$age_years + rnorm(nrow(bp_eligible), 0, 9)

nhanes_2021_2023_blood_pressure <- tibble(
  respondent_id = bp_eligible$respondent_id,
  bp_arm = sample_cat(c("right", "left"), nrow(bp_eligible), c(0.99, 0.01)),
  cuff_size = sample_cat(c("17-21.9 cm", "22-31.9 cm", "32-41.9 cm", "42-50 cm"), nrow(bp_eligible), c(0.05, 0.45, 0.44, 0.06)),
  systolic_1 = round(bp_base + rnorm(nrow(bp_eligible), 1, 4)),
  diastolic_1 = round(di_base + rnorm(nrow(bp_eligible), 1, 3)),
  systolic_2 = round(bp_base + rnorm(nrow(bp_eligible), 0, 4)),
  diastolic_2 = round(di_base + rnorm(nrow(bp_eligible), 0, 3)),
  systolic_3 = round(bp_base + rnorm(nrow(bp_eligible), -1, 4)),
  diastolic_3 = round(di_base + rnorm(nrow(bp_eligible), -1, 3)),
  pulse_1 = round(pulse_base + rnorm(nrow(bp_eligible), 0, 3)),
  pulse_2 = round(pulse_base + rnorm(nrow(bp_eligible), 0, 3)),
  pulse_3 = round(pulse_base + rnorm(nrow(bp_eligible), 0, 3))
) |>
  mutate(
    across(c(systolic_1:pulse_3), ~ if_else(runif(n()) < 0.035, NA_real_, as.numeric(.x))),
    systolic_mean = rowMeans(pick(systolic_1, systolic_2, systolic_3), na.rm = TRUE),
    diastolic_mean = rowMeans(pick(diastolic_1, diastolic_2, diastolic_3), na.rm = TRUE),
    pulse_mean = rowMeans(pick(pulse_1, pulse_2, pulse_3), na.rm = TRUE),
    systolic_mean = if_else(is.nan(systolic_mean), NA_real_, systolic_mean),
    diastolic_mean = if_else(is.nan(diastolic_mean), NA_real_, diastolic_mean),
    pulse_mean = if_else(is.nan(pulse_mean), NA_real_, pulse_mean),
    systolic_n_readings = rowSums(!is.na(pick(systolic_1, systolic_2, systolic_3))),
    diastolic_n_readings = rowSums(!is.na(pick(diastolic_1, diastolic_2, diastolic_3)))
  ) |>
  arrange(respondent_id)

write_sim_csv(nhanes_2021_2023_blood_pressure, "neighborhood_health_survey_blood_pressure_screening.csv")
write_sim_codebook("simulated_neighborhood_health_survey_blood_pressure_screening.md", "data/real/nhanes_2021_2023_blood_pressure.csv", "neighborhood blood pressure screening", "one eligible participant", "Includes three systolic/diastolic/pulse readings, occasional missing readings, and row means.")

# NHANES-style hepatitis A -----------------------------------------------------

hepa_eligible <- nhanes_2021_2023_demographics |>
  filter(age_years >= 2, interview_exam_status == "interviewed_and_examined") |>
  sample_n(min(n(), 4300))
hepa_prob <- logit(-1.6 + 0.035 * hepa_eligible$age_years + if_else(hepa_eligible$born_in_us == "no", 0.8, 0))
hepa_positive <- runif(nrow(hepa_eligible)) < hepa_prob
hepa_indeterminate <- runif(nrow(hepa_eligible)) < 0.01

nhanes_2021_2023_hepatitis_a <- tibble(
  respondent_id = hepa_eligible$respondent_id,
  phlebotomy_weight = round(runif(nrow(hepa_eligible), 4300, 255000), 6),
  hepatitis_a_antibody = case_when(
    hepa_indeterminate ~ "indeterminate",
    hepa_positive ~ "positive",
    TRUE ~ "negative"
  ),
  hepatitis_a_antibody_positive = case_when(
    hepatitis_a_antibody == "positive" ~ TRUE,
    hepatitis_a_antibody == "negative" ~ FALSE,
    TRUE ~ NA
  )
) |>
  arrange(respondent_id)

write_sim_csv(nhanes_2021_2023_hepatitis_a, "neighborhood_health_survey_hepatitis_a.csv")
write_sim_codebook("simulated_neighborhood_health_survey_hepatitis_a.md", "data/real/nhanes_2021_2023_hepatitis_a.csv", "neighborhood health survey hepatitis A antibody status", "one eligible participant", "Includes age and nativity-related antibody positivity pattern plus rare indeterminate results.")

# NHANES-style dietary foods and summaries ------------------------------------

diet_people <- nhanes_2021_2023_demographics |>
  filter(interview_exam_status == "interviewed_and_examined") |>
  sample_n(min(n(), 3400)) |>
  mutate(
    two_days = runif(n()) < 0.86,
    dietary_day1_weight = round(runif(n(), 5500, 420000), 6),
    dietary_2day_weight = if_else(two_days, round(runif(n(), 6000, 760000), 6), 0)
  )

food_codes <- c(94000100, 92101000, 24100020, 75113000, 58106200, 63107010, 11111000, 56205010, 27146100, 92512010, 32104900, 72201100)
food_profile <- tibble(
  usda_food_code = food_codes,
  base_grams = c(240, 300, 150, 80, 120, 100, 55, 180, 90, 160, 70, 200),
  kcal_per_gram = c(0, 0.01, 1.6, 0.2, 2.7, 2.1, 4.0, 1.1, 3.0, 0.7, 2.3, 1.4),
  source = c(1, 15, 3, 1, 1, 3, 1, 6, 2, 1, 14, 1)
)

simulate_food_day <- function(people, day) {
  active <- people |>
    filter(day == 1 | two_days)
  records_per_day <- sample(5:22, nrow(active), replace = TRUE)
  expanded <- active[rep(seq_len(nrow(active)), records_per_day), ] |>
    group_by(respondent_id) |>
    mutate(food_line = row_number()) |>
    ungroup()
  n <- nrow(expanded)
  chosen <- sample(seq_len(nrow(food_profile)), n, replace = TRUE, prob = c(0.18, 0.10, 0.08, 0.10, 0.12, 0.08, 0.08, 0.07, 0.05, 0.08, 0.03, 0.03))
  grams <- rgamma(n, shape = 3, scale = food_profile$base_grams[chosen] / 3)
  kcal <- pmax(0, grams * food_profile$kcal_per_gram[chosen] + rnorm(n, 0, 8))
  source_code <- food_profile$source[chosen]
  tibble(
    respondent_id = expanded$respondent_id,
    dietary_day = day,
    dietary_day1_weight = expanded$dietary_day1_weight,
    dietary_2day_weight = expanded$dietary_2day_weight,
    food_line = expanded$food_line,
    recall_status = "reliable",
    breastfed_infant_either_day = if_else(expanded$age_years < 1 & runif(n) < 0.25, "yes", "no"),
    intake_days_available = if_else(expanded$two_days, 2, 1),
    days_between_intake_and_household_interview = sample(-20:120, n, replace = TRUE),
    intake_weekday = sample_cat(c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), n),
    interview_language = sample_cat(c("English", "Spanish", "English and Spanish", "Other"), n, c(0.88, 0.10, 0.015, 0.005)),
    combination_food_number = sample(0:8, n, replace = TRUE, prob = c(0.60, rep(0.05, 8))),
    combination_food_type = sample_cat(c("Not in combination", "Beverage with additions", "Cereal with additions", "Salad", "Sandwiches", "Other mixtures"), n, c(0.60, 0.10, 0.06, 0.08, 0.09, 0.07)),
    eating_time = sprintf("%02d:%02d:00", sample(6:23, n, replace = TRUE), sample(c(0, 15, 30, 45), n, replace = TRUE)),
    eating_occasion = sample_cat(c("Breakfast", "Lunch", "Dinner", "Supper", "Snack", "Beverage/Drink"), n, c(0.20, 0.23, 0.25, 0.05, 0.20, 0.07)),
    food_source_code = source_code,
    food_source = food_source_label(source_code),
    food_source_group = food_source_group(source_code),
    eaten_at_home = sample_cat(c("yes", "no"), n, c(0.68, 0.32)),
    usda_food_code = food_profile$usda_food_code[chosen],
    grams = round(grams, 2),
    energy_kcal = round(kcal),
    protein_g = round(pmax(0, kcal * runif(n, 0.025, 0.07) / 4), 2),
    carbohydrate_g = round(pmax(0, kcal * runif(n, 0.35, 0.62) / 4), 2),
    total_sugars_g = round(pmax(0, kcal * runif(n, 0.03, 0.22) / 4), 2),
    dietary_fiber_g = round(pmax(0, kcal * runif(n, 0.003, 0.025) / 2), 2),
    total_fat_g = round(pmax(0, kcal * runif(n, 0.18, 0.45) / 9), 2),
    saturated_fat_g = round(pmax(0, kcal * runif(n, 0.04, 0.16) / 9), 3),
    cholesterol_mg = round(pmax(0, rnorm(n, kcal * 0.05, 12))),
    sodium_mg = round(pmax(0, kcal * runif(n, 0.55, 1.7))),
    potassium_mg = round(pmax(0, kcal * runif(n, 0.3, 1.6))),
    caffeine_mg = round(if_else(usda_food_code %in% c(92101000), runif(n, 20, 160), runif(n, 0, 5))),
    alcohol_g = round(if_else(expanded$age_years >= 21 & runif(n) < 0.06, runif(n, 3, 28), 0), 1)
  )
}

nhanes_2021_2023_dietary_foods <- bind_rows(
  simulate_food_day(diet_people, 1),
  simulate_food_day(diet_people, 2)
) |>
  arrange(respondent_id, dietary_day, food_line)

write_sim_csv(nhanes_2021_2023_dietary_foods, "neighborhood_health_survey_dietary_foods.csv")
write_sim_codebook("simulated_neighborhood_health_survey_dietary_foods.md", "data/real/nhanes_2021_2023_dietary_foods.csv", "neighborhood health survey item-level dietary recall", "one reported food/beverage item", "Includes Day 1/Day 2 long records, eating occasions, food sources, and selected nutrient components.")

nhanes_2021_2023_dietary_daily_summary <- nhanes_2021_2023_dietary_foods |>
  group_by(respondent_id, dietary_day) |>
  summarise(
    dietary_day1_weight = first(dietary_day1_weight),
    dietary_2day_weight = first(dietary_2day_weight),
    recall_status = first(recall_status),
    breastfed_infant_either_day = first(breastfed_infant_either_day),
    intake_days_available = first(intake_days_available),
    intake_weekday = first(intake_weekday),
    n_food_records = n(),
    n_eating_occasions = n_distinct(eating_occasion, na.rm = TRUE),
    total_grams = sum(grams, na.rm = TRUE),
    energy_kcal = sum(energy_kcal, na.rm = TRUE),
    protein_g = sum(protein_g, na.rm = TRUE),
    carbohydrate_g = sum(carbohydrate_g, na.rm = TRUE),
    total_sugars_g = sum(total_sugars_g, na.rm = TRUE),
    dietary_fiber_g = sum(dietary_fiber_g, na.rm = TRUE),
    total_fat_g = sum(total_fat_g, na.rm = TRUE),
    saturated_fat_g = sum(saturated_fat_g, na.rm = TRUE),
    cholesterol_mg = sum(cholesterol_mg, na.rm = TRUE),
    sodium_mg = sum(sodium_mg, na.rm = TRUE),
    potassium_mg = sum(potassium_mg, na.rm = TRUE),
    caffeine_mg = sum(caffeine_mg, na.rm = TRUE),
    alcohol_g = sum(alcohol_g, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    sugars_g_per_1000_kcal = if_else(energy_kcal > 0, total_sugars_g / energy_kcal * 1000, NA_real_),
    sodium_mg_per_1000_kcal = if_else(energy_kcal > 0, sodium_mg / energy_kcal * 1000, NA_real_)
  ) |>
  arrange(respondent_id, dietary_day)

write_sim_csv(nhanes_2021_2023_dietary_daily_summary, "neighborhood_health_survey_dietary_daily_summary.csv")
write_sim_codebook("simulated_neighborhood_health_survey_dietary_daily_summary.md", "data/real/nhanes_2021_2023_dietary_daily_summary.csv", "neighborhood health survey daily nutrient summaries", "one participant-day", "Generated by summing the simulated item-level dietary records.")

nhanes_2021_2023_dietary_person_summary <- nhanes_2021_2023_dietary_daily_summary |>
  group_by(respondent_id) |>
  summarise(
    dietary_days = n_distinct(dietary_day),
    mean_daily_energy_kcal = mean(energy_kcal, na.rm = TRUE),
    mean_daily_total_sugars_g = mean(total_sugars_g, na.rm = TRUE),
    mean_daily_dietary_fiber_g = mean(dietary_fiber_g, na.rm = TRUE),
    mean_daily_total_fat_g = mean(total_fat_g, na.rm = TRUE),
    mean_daily_saturated_fat_g = mean(saturated_fat_g, na.rm = TRUE),
    mean_daily_sodium_mg = mean(sodium_mg, na.rm = TRUE),
    mean_daily_potassium_mg = mean(potassium_mg, na.rm = TRUE),
    mean_daily_caffeine_mg = mean(caffeine_mg, na.rm = TRUE),
    mean_daily_alcohol_g = mean(alcohol_g, na.rm = TRUE),
    .groups = "drop"
  ) |>
  left_join(
    nhanes_2021_2023_dietary_daily_summary |>
      select(respondent_id, dietary_day, energy_kcal, total_sugars_g, sodium_mg) |>
      pivot_wider(names_from = dietary_day, values_from = c(energy_kcal, total_sugars_g, sodium_mg), names_glue = "day{dietary_day}_{.value}"),
    by = "respondent_id"
  ) |>
  arrange(respondent_id)

write_sim_csv(nhanes_2021_2023_dietary_person_summary, "neighborhood_health_survey_dietary_person_summary.csv")
write_sim_codebook("simulated_neighborhood_health_survey_dietary_person_summary.md", "data/real/nhanes_2021_2023_dietary_person_summary.csv", "neighborhood health survey person-level dietary means", "one participant with dietary records", "Generated by averaging available simulated recall-day summaries.")

nhanes_2021_2023_analysis <- nhanes_2021_2023_demographics |>
  left_join(nhanes_2021_2023_blood_pressure, by = "respondent_id") |>
  left_join(nhanes_2021_2023_hepatitis_a, by = "respondent_id") |>
  left_join(nhanes_2021_2023_dietary_person_summary, by = "respondent_id") |>
  mutate(
    adult_high_bp_range = case_when(
      age_years < 18 ~ NA,
      is.na(systolic_mean) | is.na(diastolic_mean) ~ NA,
      systolic_mean >= 130 | diastolic_mean >= 80 ~ TRUE,
      TRUE ~ FALSE
    ),
    adult_bp_category_simplified = case_when(
      age_years < 18 ~ NA_character_,
      is.na(systolic_mean) | is.na(diastolic_mean) ~ NA_character_,
      systolic_mean >= 140 | diastolic_mean >= 90 ~ "stage_2_range",
      systolic_mean >= 130 | diastolic_mean >= 80 ~ "stage_1_range",
      systolic_mean >= 120 & diastolic_mean < 80 ~ "elevated_range",
      systolic_mean < 120 & diastolic_mean < 80 ~ "normal_range",
      TRUE ~ NA_character_
    )
  ) |>
  arrange(respondent_id)

write_sim_csv(nhanes_2021_2023_analysis, "neighborhood_health_survey_analysis.csv")
write_sim_codebook("simulated_neighborhood_health_survey_analysis.md", "data/real/nhanes_2021_2023_analysis.csv", "joined neighborhood health survey analysis file", "one participant", "Joins the simulated demographics, blood pressure, hepatitis A, and dietary person summaries for low-friction EDA practice.")

# PRAMS-style subgroup estimates ----------------------------------------------

sim_states <- tibble(
  location_abbr = c(state.abb, "DC"),
  location = c(state.name, "District of Columbia")
)

subgroup_grid <- tribble(
  ~subgroup_cat, ~subgroup,
  "Age group", "Under 25",
  "Age group", "25-34",
  "Age group", "35 or older",
  "Insurance type", "Private",
  "Insurance type", "Public",
  "Insurance type", "Uninsured",
  "Prenatal care", "Early care",
  "Prenatal care", "Later or no care",
  "Birth history", "First birth",
  "Birth history", "Previous birth"
)

prams_2011_selected <- tidyr::crossing(sim_states, subgroup_grid) |>
  mutate(
    subgroup_shift = case_when(
      subgroup %in% c("Under 25", "Public", "Uninsured", "Later or no care") ~ 5,
      subgroup %in% c("Private", "Early care") ~ -3,
      TRUE ~ 0
    ),
    state_shift = rnorm(n_distinct(location_abbr))[match(location_abbr, unique(location_abbr))],
    depression_within_3_months_birth = pmax(2, pmin(38, 15 + subgroup_shift + state_shift * 2 + rnorm(n(), 0, 3))),
    anxiety_within_3_months_birth = pmax(3, pmin(45, 20 + subgroup_shift + state_shift * 2 + rnorm(n(), 0, 4))),
    binge_drinking_within_3_months_birth = pmax(0, pmin(18, 5 - subgroup_shift * 0.2 + state_shift + rnorm(n(), 0, 2))),
    alcohol_use_within_3_months_birth = pmax(2, pmin(35, 11 - subgroup_shift * 0.3 + state_shift + rnorm(n(), 0, 3))),
    across(ends_with("birth"), ~ if_else(runif(n()) < 0.06, NA_real_, round(.x, 1)))
  ) |>
  select(
    location_abbr,
    location,
    subgroup_cat,
    subgroup,
    depression_within_3_months_birth,
    anxiety_within_3_months_birth,
    binge_drinking_within_3_months_birth,
    alcohol_use_within_3_months_birth
  ) |>
  arrange(location_abbr, subgroup_cat, subgroup)

write_sim_csv(prams_2011_selected, "new_parent_wellness_survey.csv")
write_sim_codebook("simulated_new_parent_wellness_survey.md", "data/real/prams_2011_selected.csv", "new-parent wellness subgroup estimates", "one place-subgroup row", "Mirrors the PRAMS subgroup estimate shape with simulated postpartum wellness indicators and some missing subgroup estimates.")

prams_state_overall_wide <- prams_2011_selected |>
  group_by(location_abbr, location) |>
  summarise(
    depression_percent = mean(depression_within_3_months_birth, na.rm = TRUE),
    anxiety_percent = mean(anxiety_within_3_months_birth, na.rm = TRUE),
    binge_drinking_percent = mean(binge_drinking_within_3_months_birth, na.rm = TRUE),
    alcohol_use_percent = mean(alcohol_use_within_3_months_birth, na.rm = TRUE),
    .groups = "drop"
  ) |>
  transmute(
    state = location_abbr,
    state_name = location,
    across(ends_with("percent"), ~ round(.x, 1))
  ) |>
  arrange(state)

prams_previous_live_births_wide <- prams_2011_selected |>
  filter(subgroup_cat == "Birth history") |>
  mutate(
    subgroup = case_when(
      subgroup == "First birth" ~ "no_previous_live_births",
      subgroup == "Previous birth" ~ "one_or_more_previous_live_births",
      TRUE ~ str_to_lower(str_replace_all(subgroup, "[^a-zA-Z0-9]+", "_"))
    )
  ) |>
  select(location_abbr, location, subgroup, depression_within_3_months_birth, anxiety_within_3_months_birth, binge_drinking_within_3_months_birth, alcohol_use_within_3_months_birth) |>
  pivot_wider(names_from = subgroup, values_from = c(depression_within_3_months_birth, anxiety_within_3_months_birth, binge_drinking_within_3_months_birth, alcohol_use_within_3_months_birth)) |>
  transmute(
    state = location_abbr,
    state_name = location,
    depression_within_3_months_birth_no_previous_live_births,
    depression_within_3_months_birth_one_or_more_previous_live_births,
    anxiety_within_3_months_birth_no_previous_live_births,
    anxiety_within_3_months_birth_one_or_more_previous_live_births,
    binge_drinking_within_3_months_birth_no_previous_live_births,
    binge_drinking_within_3_months_birth_one_or_more_previous_live_births,
    alcohol_use_within_3_months_birth_no_previous_live_births,
    alcohol_use_within_3_months_birth_one_or_more_previous_live_births,
    depression_difference_one_or_more_minus_none = depression_within_3_months_birth_one_or_more_previous_live_births - depression_within_3_months_birth_no_previous_live_births,
    binge_difference_one_or_more_minus_none = binge_drinking_within_3_months_birth_one_or_more_previous_live_births - binge_drinking_within_3_months_birth_no_previous_live_births
  ) |>
  mutate(across(where(is.numeric), ~ round(.x, 1))) |>
  arrange(state)

write_sim_csv(prams_state_overall_wide, "new_parent_wellness_state_overall_wide.csv")
write_sim_codebook("simulated_new_parent_wellness_state_overall_wide.md", "data/real/wide/prams_state_overall_wide.csv", "new-parent wellness state overall wide", "one state row", "Mirrors the PRAMS state overall wide shape with simulated state-level indicator summaries.")
write_sim_csv(prams_previous_live_births_wide, "new_parent_previous_births_wide.csv")
write_sim_codebook("simulated_new_parent_previous_births_wide.md", "data/real/wide/prams_previous_live_births_wide.csv", "new-parent wellness by previous births", "one state row", "Mirrors the PRAMS previous-live-births wide shape with simulated subgroup indicator differences.")

# Flu-style seasonal coverage --------------------------------------------------

flu_age_groups <- c("6 Months - 4 Years", "5-12 Years", "13-17 Years", "18-49 Years", "50-64 Years", ">=65 Years")
flu_geographies <- c("National", paste("Region", 1:10))
flu_season_years <- 2015:2024

flu_vaccination_age_time_clean <- tidyr::crossing(
  season_start_year = flu_season_years,
  month = 1:12,
  geography = flu_geographies,
  age_group = flu_age_groups
) |>
  mutate(
    season = paste0(season_start_year, "-", str_sub(as.character(season_start_year + 1), 3, 4)),
    geography_type = "HHS Regions/National",
    fips = if_else(geography == "National", 0, 100 + as.integer(str_extract(geography, "[0-9]+"))),
    age_effect = case_when(
      age_group == "6 Months - 4 Years" ~ -10,
      age_group == "5-12 Years" ~ 2,
      age_group == "13-17 Years" ~ -2,
      age_group == "18-49 Years" ~ -18,
      age_group == "50-64 Years" ~ -5,
      age_group == ">=65 Years" ~ 12,
      TRUE ~ 0
    ),
    month_effect = pmin(month, 8) * 4.2,
    region_effect = if_else(geography == "National", 0, rnorm(length(flu_geographies))[match(geography, flu_geographies)]),
    estimate = pmax(1, pmin(92, 15 + age_effect + month_effect + region_effect + rnorm(n(), 0, 4))),
    ci_width = runif(n(), 2.5, 7.5),
    ci_lower = pmax(0, estimate - ci_width),
    ci_upper = pmin(100, estimate + ci_width),
    sample_size = round(runif(n(), 250, 5500)),
    across(c(estimate, ci_lower, ci_upper), ~ round(.x, 1))
  ) |>
  select(season, season_start_year, month, geography_type, geography, fips, age_group, estimate, ci_lower, ci_upper, sample_size) |>
  arrange(season_start_year, month, geography, age_group)

write_sim_csv(flu_vaccination_age_time_clean, "respiratory_booster_coverage.csv")
write_sim_codebook("simulated_respiratory_booster_coverage.md", "data/real/flu_vaccination_age_time_clean.csv", "seasonal respiratory booster coverage", "one geography-age-month row", "Mirrors the flu coverage time-series shape with age, region, month, and season patterns.")

age_key <- function(x) {
  x |>
    str_to_lower() |>
    str_replace_all(">=", "ge_") |>
    str_replace_all("[^a-z0-9]+", "_") |>
    str_replace_all("(^_|_$)", "")
}

flu_vaccination_age_month_wide <- flu_vaccination_age_time_clean |>
  mutate(age_group = age_key(age_group)) |>
  select(season, season_start_year, month, geography, age_group, estimate, ci_lower, ci_upper, sample_size) |>
  pivot_wider(
    names_from = age_group,
    values_from = c(estimate, ci_lower, ci_upper, sample_size)
  ) |>
  select(
    season,
    season_start_year,
    month,
    geography,
    estimate_50_64_years,
    estimate_ge_65_years,
    estimate_6_months_4_years,
    estimate_5_12_years,
    estimate_13_17_years,
    estimate_18_49_years,
    ci_lower_50_64_years,
    ci_lower_ge_65_years,
    ci_lower_6_months_4_years,
    ci_lower_5_12_years,
    ci_lower_13_17_years,
    ci_lower_18_49_years,
    ci_upper_50_64_years,
    ci_upper_ge_65_years,
    ci_upper_6_months_4_years,
    ci_upper_5_12_years,
    ci_upper_13_17_years,
    ci_upper_18_49_years,
    sample_size_50_64_years,
    sample_size_ge_65_years,
    sample_size_6_months_4_years,
    sample_size_5_12_years,
    sample_size_13_17_years,
    sample_size_18_49_years
  ) |>
  arrange(season_start_year, month, geography)

flu_national_months <- flu_vaccination_age_time_clean |>
  filter(geography == "National") |>
  group_by(season, season_start_year) |>
  summarise(n_months = n_distinct(month), .groups = "drop")

flu_vaccination_us_age_season_wide <- flu_vaccination_age_time_clean |>
  filter(geography == "National") |>
  mutate(age_group = age_key(age_group)) |>
  group_by(season, season_start_year, age_group) |>
  summarise(
    mean_estimate = mean(estimate, na.rm = TRUE),
    mean_ci_lower = mean(ci_lower, na.rm = TRUE),
    mean_ci_upper = mean(ci_upper, na.rm = TRUE),
    total_sample_size = sum(sample_size, na.rm = TRUE),
    .groups = "drop"
  ) |>
  pivot_wider(
    names_from = age_group,
    values_from = c(mean_estimate, mean_ci_lower, mean_ci_upper, total_sample_size)
  ) |>
  left_join(flu_national_months, by = c("season", "season_start_year")) |>
  select(
    season,
    season_start_year,
    n_months,
    mean_estimate_50_64_years,
    mean_estimate_ge_65_years,
    mean_estimate_13_17_years,
    mean_estimate_18_49_years,
    mean_estimate_5_12_years,
    mean_estimate_6_months_4_years,
    mean_ci_lower_50_64_years,
    mean_ci_lower_ge_65_years,
    mean_ci_lower_13_17_years,
    mean_ci_lower_18_49_years,
    mean_ci_lower_5_12_years,
    mean_ci_lower_6_months_4_years,
    mean_ci_upper_50_64_years,
    mean_ci_upper_ge_65_years,
    mean_ci_upper_13_17_years,
    mean_ci_upper_18_49_years,
    mean_ci_upper_5_12_years,
    mean_ci_upper_6_months_4_years,
    total_sample_size_50_64_years,
    total_sample_size_ge_65_years,
    total_sample_size_13_17_years,
    total_sample_size_18_49_years,
    total_sample_size_5_12_years,
    total_sample_size_6_months_4_years
  ) |>
  mutate(across(starts_with("mean_"), ~ round(.x, 1))) |>
  arrange(season_start_year)

write_sim_csv(flu_vaccination_age_month_wide, "respiratory_booster_age_month_wide.csv")
write_sim_codebook("simulated_respiratory_booster_age_month_wide.md", "data/real/wide/flu_vaccination_age_month_wide.csv", "respiratory booster age-month wide", "one season-month-geography row", "Mirrors the flu vaccination age-month wide shape with simulated respiratory booster estimates.")
write_sim_csv(flu_vaccination_us_age_season_wide, "respiratory_booster_us_age_season_wide.csv")
write_sim_codebook("simulated_respiratory_booster_us_age_season_wide.md", "data/real/wide/flu_vaccination_us_age_season_wide.csv", "respiratory booster national age-season wide", "one season row", "Mirrors the national flu age-season wide shape with simulated respiratory booster summaries.")

# Census-style state group composition ----------------------------------------

state_population_ranks <- tibble(
  state = c(state.abb, "DC"),
  state_name = c(state.name, "District of Columbia"),
  population = round(rlnorm(51, log(4500000), 0.85))
) |>
  arrange(desc(population)) |>
  mutate(rank = row_number()) |>
  arrange(rank)

race_groups <- c(
  "American Indian and Alaska Native",
  "Asian",
  "Black",
  "Hispanic or Latino",
  "Native Hawaiian and Other Pacific Islander",
  "Other",
  "White"
)

share_matrix <- matrix(rexp(51 * length(race_groups), rate = c(18, 6, 5, 4, 30, 15, 2)), nrow = 51, byrow = TRUE)
share_matrix <- share_matrix / rowSums(share_matrix)

census_state_race_ethnicity_long <- state_population_ranks |>
  mutate(total_race_ethnicity_population = population) |>
  select(state, state_name, rank, total_population = population, total_race_ethnicity_population) |>
  bind_cols(as_tibble(share_matrix, .name_repair = ~ race_groups)) |>
  pivot_longer(cols = all_of(race_groups), names_to = "race_ethnicity", values_to = "share") |>
  mutate(
    race_ethnicity_population = round(total_race_ethnicity_population * share),
    share = race_ethnicity_population / total_race_ethnicity_population
  ) |>
  select(state, state_name, rank, total_population, race_ethnicity, race_ethnicity_population, total_race_ethnicity_population, share) |>
  arrange(rank, race_ethnicity)

state_race_population_summary <- census_state_race_ethnicity_long |>
  select(state, state_name, rank, total_population, race_ethnicity, share) |>
  mutate(
    race_ethnicity = str_to_lower(race_ethnicity),
    race_ethnicity = str_replace_all(race_ethnicity, "[^a-z0-9]+", "_"),
    race_ethnicity = str_replace_all(race_ethnicity, "(^_|_$)", "")
  ) |>
  pivot_wider(names_from = race_ethnicity, values_from = share, names_prefix = "share_") |>
  select(
    state,
    state_name,
    rank,
    total_population,
    share_american_indian_and_alaska_native,
    share_asian,
    share_black,
    share_hispanic_or_latino,
    share_native_hawaiian_and_other_pacific_islander,
    share_other,
    share_white
  ) |>
  arrange(rank)

write_sim_csv(census_state_race_ethnicity_long, "state_school_enrollment_groups_long.csv")
write_sim_codebook("simulated_state_school_enrollment_groups_long.md", "data/real/census_state_race_ethnicity_long.csv", "fictional state school enrollment composition", "one state-group row", "Mirrors state composition data with simulated enrollment group shares and populations.")
write_sim_csv(state_population_ranks, "state_enrollment_ranks.csv")
write_sim_codebook("simulated_state_enrollment_ranks.md", "data/real/state_population_ranks.csv", "fictional state enrollment ranks", "one state row", "Mirrors state population ranks with simulated enrollment totals.")
write_sim_csv(state_race_population_summary, "state_enrollment_group_summary.csv")
write_sim_codebook("simulated_state_enrollment_group_summary.md", "data/real/state_race_population_summary.csv", "fictional state enrollment group summary", "one state row", "Mirrors the wide state composition summary with simulated group shares.")

census_state_race_ethnicity_wide <- census_state_race_ethnicity_long |>
  mutate(
    race_ethnicity = str_to_lower(race_ethnicity),
    race_ethnicity = str_replace_all(race_ethnicity, "[^a-z0-9]+", "_"),
    race_ethnicity = str_replace_all(race_ethnicity, "(^_|_$)", "")
  ) |>
  select(state, state_name, rank, total_population, race_ethnicity, race_ethnicity_population, share) |>
  pivot_wider(
    names_from = race_ethnicity,
    values_from = c(race_ethnicity_population, share)
  ) |>
  mutate(state_population_weight = total_population / sum(total_population, na.rm = TRUE)) |>
  select(
    state,
    state_name,
    rank,
    total_population,
    race_ethnicity_population_american_indian_and_alaska_native,
    race_ethnicity_population_asian,
    race_ethnicity_population_black,
    race_ethnicity_population_hispanic_or_latino,
    race_ethnicity_population_native_hawaiian_and_other_pacific_islander,
    race_ethnicity_population_other,
    race_ethnicity_population_white,
    share_american_indian_and_alaska_native,
    share_asian,
    share_black,
    share_hispanic_or_latino,
    share_native_hawaiian_and_other_pacific_islander,
    share_other,
    share_white,
    state_population_weight
  ) |>
  arrange(rank)

write_sim_csv(census_state_race_ethnicity_wide, "state_school_enrollment_groups_wide.csv")
write_sim_codebook("simulated_state_school_enrollment_groups_wide.md", "data/real/wide/census_state_race_ethnicity_wide.csv", "fictional state school enrollment groups wide", "one state row", "Mirrors the wide Census state composition file with simulated enrollment group counts and shares.")

# PLACES-style county and tract wellness indicators ----------------------------

wellness_measures <- tibble(
  measure_key = c("current_smoking", "diabetes", "frequent_mental_distress", "high_blood_pressure", "lack_health_insurance", "obesity", "physical_inactivity"),
  measure_id = c("CSMOKING", "DIABETES", "MHLTH", "BPHIGH", "ACCESS2", "OBESITY", "LPA"),
  measure = c("Current smoking", "Diabetes", "Frequent mental distress", "High blood pressure", "Lack of health insurance", "Obesity", "Physical inactivity"),
  base = c(14, 10, 15, 31, 11, 33, 25)
)

n_counties <- 520
county_base <- tibble(
  year = 2023,
  state = sample(state.abb, n_counties, replace = TRUE),
  county_id = seq_len(n_counties),
  tract_count = sample(1:80, n_counties, replace = TRUE),
  total_population = round(rlnorm(n_counties, log(65000), 1.0)),
  total_adult_population = round(total_population * runif(n_counties, 0.68, 0.84)),
  vulnerability = rnorm(n_counties)
) |>
  mutate(
    state_name = state.name[match(state, state.abb)],
    county_fips = sprintf("%02d%03d", match(state, state.abb), county_id %% 999),
    county_name = paste("County", str_pad(county_id, 3, pad = "0"))
  )

places_county_core_measures_long <- tidyr::crossing(county_base, wellness_measures) |>
  mutate(
    estimate = pmax(1, pmin(60, base + 4 * vulnerability + rnorm(n(), 0, 3))),
    ci_width = runif(n(), 1.5, 5.5) + 35000 / pmax(total_adult_population, 2000),
    ci_lower = pmax(0, estimate - ci_width),
    ci_upper = pmin(100, estimate + ci_width),
    across(c(estimate, ci_lower, ci_upper), ~ round(.x, 1))
  ) |>
  select(year, state, state_name, county_fips, county_name, tract_count, total_population, total_adult_population, measure_id, measure_key, measure, estimate, ci_lower, ci_upper) |>
  arrange(state, county_name, measure_key)

places_county_core_measures_wide <- places_county_core_measures_long |>
  select(year, state, state_name, county_fips, county_name, tract_count, total_population, total_adult_population, measure_key, estimate) |>
  pivot_wider(names_from = measure_key, values_from = estimate) |>
  select(year, state, state_name, county_fips, county_name, tract_count, total_population, total_adult_population, current_smoking, diabetes, frequent_mental_distress, high_blood_pressure, lack_health_insurance, obesity, physical_inactivity) |>
  arrange(state, county_name)

write_sim_csv(places_county_core_measures_long, "county_wellness_indicators_long.csv")
write_sim_codebook("simulated_county_wellness_indicators_long.md", "data/real/places_county_core_measures_long.csv", "county wellness indicators", "one county-measure row", "Mirrors the PLACES county long shape with simulated county wellness indicators.")
write_sim_csv(places_county_core_measures_wide, "county_wellness_indicators_wide.csv")
write_sim_codebook("simulated_county_wellness_indicators_wide.md", "data/real/places_county_core_measures_wide.csv", "county wellness indicators wide", "one county row", "Mirrors the PLACES county wide shape with simulated county wellness indicators.")

metro_tracts <- tibble(
  year = 2023,
  state = sample(c("DC", "MD", "VA"), 700, replace = TRUE, prob = c(0.12, 0.40, 0.48)),
  tract_index = seq_len(700),
  total_population = round(rlnorm(700, log(4200), 0.45)),
  longitude = runif(700, -78.5, -76.7),
  latitude = runif(700, 37.0, 39.4),
  vulnerability = rnorm(700)
) |>
  mutate(
    state_name = case_when(state == "DC" ~ "District of Columbia", state == "MD" ~ "Maryland", TRUE ~ "Virginia"),
    county_name = paste("Metro County", sample(1:18, n(), replace = TRUE)),
    county_fips = as.numeric(sprintf("%02d%03d", match(state, c("DC", "MD", "VA")) + 10, sample(1:199, n(), replace = TRUE))),
    tract_fips = as.numeric(paste0(county_fips, str_pad(tract_index %% 999999, 6, pad = "0"))),
    location_id = tract_fips,
    total_adult_population = round(total_population * runif(n(), 0.66, 0.84))
  )

places_tract_dc_md_va_core_measures_long <- tidyr::crossing(metro_tracts, wellness_measures) |>
  mutate(
    estimate = pmax(1, pmin(65, base + 5 * vulnerability + rnorm(n(), 0, 4))),
    ci_width = runif(n(), 2, 7),
    ci_lower = pmax(0, estimate - ci_width),
    ci_upper = pmin(100, estimate + ci_width),
    across(c(estimate, ci_lower, ci_upper), ~ round(.x, 1))
  ) |>
  select(year, state, state_name, county_name, county_fips, tract_fips, location_id, measure_id, measure_key, measure, estimate, ci_lower, ci_upper, total_population, total_adult_population, longitude, latitude) |>
  arrange(state, county_name, tract_fips, measure_key)

write_sim_csv(places_tract_dc_md_va_core_measures_long, "metro_neighborhood_wellness_indicators_long.csv")
write_sim_codebook("simulated_metro_neighborhood_wellness_indicators_long.md", "data/real/places_tract_dc_md_va_core_measures_long.csv", "metro neighborhood wellness indicators", "one tract-measure row", "Mirrors the PLACES tract long shape for a fictional DC/MD/VA-style metro area.")

# EPA-style county monitoring data --------------------------------------------

metric_lookup <- tibble(
  metric_key = c("co_8hr_ppm", "lead_3mo_ug_m3", "no2_annual_mean_ppb", "no2_1hr_ppb", "ozone_8hr_ppb", "pm10_24hr_ug_m3", "pm25_annual_mean_ug_m3", "pm25_24hr_ug_m3", "so2_1hr_ppb", "so2_annual_mean_ppb"),
  pollutant = c("Hum", "Echo", "Traffic rumble", "Traffic spike", "Siren", "Construction dust", "Fine dust", "Fine dust spike", "Generator", "Generator annual"),
  statistic = c("8-hour", "3-month", "annual mean", "1-hour", "8-hour", "24-hour", "weighted annual mean", "24-hour", "1-hour", "weighted annual mean"),
  unit = c("index", "index", "index", "index", "index", "index", "index", "index", "index", "index"),
  naaqs_standard = c(9, 0.15, 53, 100, 70, 150, 9, 35, 75, 10),
  typical_fraction = c(0.35, 0.25, 0.45, 0.40, 0.65, 0.35, 0.75, 0.60, 0.25, 0.45)
)

n_monitor_counties <- 320
monitor_counties <- tibble(
  year = 2025,
  state = sample(state.abb, n_monitor_counties, replace = TRUE),
  county_index = seq_len(n_monitor_counties),
  population_2020 = round(rlnorm(n_monitor_counties, log(95000), 0.9))
) |>
  mutate(
    state_name = state.name[match(state, state.abb)],
    county_fips = sprintf("%02d%03d", match(state, state.abb), county_index %% 999),
    county_name = paste("Monitoring County", str_pad(county_index, 3, pad = "0"))
  )

epa_air_quality_county_2025_long <- tidyr::crossing(monitor_counties, metric_lookup) |>
  mutate(
    status = sample_cat(c("reported", "no_data", "insufficient_data"), n(), c(0.62, 0.31, 0.07)),
    value = if_else(status == "reported", naaqs_standard * pmax(0.02, rlnorm(n(), log(typical_fraction), 0.45)), NA_real_),
    value_as_fraction_of_standard = value / naaqs_standard,
    exceeds_standard = case_when(status != "reported" ~ NA, value > naaqs_standard ~ TRUE, TRUE ~ FALSE),
    value = round(value, 3),
    value_as_fraction_of_standard = round(value_as_fraction_of_standard, 3)
  ) |>
  select(year, state, state_name, county_fips, county_name, population_2020, pollutant, statistic, unit, metric_key, value, status, naaqs_standard, value_as_fraction_of_standard, exceeds_standard) |>
  arrange(state, county_name, pollutant, statistic)

epa_values <- epa_air_quality_county_2025_long |>
  select(year, state, state_name, county_fips, county_name, population_2020, metric_key, value) |>
  pivot_wider(names_from = metric_key, values_from = value)

epa_status <- epa_air_quality_county_2025_long |>
  select(year, state, state_name, county_fips, county_name, metric_key, status) |>
  mutate(metric_key = paste0(metric_key, "_status")) |>
  pivot_wider(names_from = metric_key, values_from = status)

epa_air_quality_county_2025_wide <- epa_values |>
  left_join(epa_status, by = c("year", "state", "state_name", "county_fips", "county_name")) |>
  select(year, state, state_name, county_fips, county_name, population_2020, co_8hr_ppm, lead_3mo_ug_m3, no2_1hr_ppb, no2_annual_mean_ppb, ozone_8hr_ppb, pm10_24hr_ug_m3, pm25_24hr_ug_m3, pm25_annual_mean_ug_m3, so2_1hr_ppb, so2_annual_mean_ppb, co_8hr_ppm_status, lead_3mo_ug_m3_status, no2_1hr_ppb_status, no2_annual_mean_ppb_status, ozone_8hr_ppb_status, pm10_24hr_ug_m3_status, pm25_24hr_ug_m3_status, pm25_annual_mean_ug_m3_status, so2_1hr_ppb_status, so2_annual_mean_ppb_status) |>
  arrange(state, county_name)

write_sim_csv(epa_air_quality_county_2025_long, "county_noise_exposure_2025_long.csv")
write_sim_codebook("simulated_county_noise_exposure_2025_long.md", "data/real/epa_air_quality_county_2025_long.csv", "county noise/exposure monitoring long data", "one county-metric row", "Mirrors the EPA monitoring long shape with simulated environmental exposure metrics and missing monitoring statuses.")
write_sim_csv(epa_air_quality_county_2025_wide, "county_noise_exposure_2025_wide.csv")
write_sim_codebook("simulated_county_noise_exposure_2025_wide.md", "data/real/epa_air_quality_county_2025_wide.csv", "county noise/exposure monitoring wide data", "one county row", "Mirrors the EPA monitoring wide shape with simulated values and status columns.")

# Real-to-simulated crosswalk --------------------------------------------------

simulated_dataset_crosswalk <- tribble(
  ~real_file, ~simulated_file, ~analog_topic,
  "data/real/davis_height_weight.csv", "data/simulated/measured_vs_self_reported_exercise_minutes.csv", "measured vs self-reported exercise minutes",
  "data/real/migraine_headache_diary.csv", "data/simulated/toothache_diary.csv", "toothache diary",
  "data/real/titanic_passengers.csv", "data/simulated/boaty_mcboatface_passengers.csv", "fictional boat passenger survival",
  "data/real/infant_mortality_countries.csv", "data/simulated/rural_health_indicators.csv", "rural health indicators",
  "data/real/ginzberg_depression.csv", "data/simulated/stress_beliefs_survey.csv", "stress beliefs survey",
  "data/real/exercise_eating_disorders.csv", "data/simulated/physical_therapy_activity.csv", "physical therapy activity",
  "data/real/post_coma_recovery.csv", "data/simulated/injury_recovery_followup.csv", "injury recovery follow-up",
  "data/real/nhanes_2021_2023_demographics.csv", "data/simulated/neighborhood_health_survey_demographics.csv", "neighborhood health survey demographics",
  "data/real/nhanes_2021_2023_blood_pressure.csv", "data/simulated/neighborhood_health_survey_blood_pressure_screening.csv", "neighborhood blood pressure screening",
  "data/real/nhanes_2021_2023_hepatitis_a.csv", "data/simulated/neighborhood_health_survey_hepatitis_a.csv", "neighborhood hepatitis A antibody status",
  "data/real/nhanes_2021_2023_dietary_foods.csv", "data/simulated/neighborhood_health_survey_dietary_foods.csv", "neighborhood dietary food records",
  "data/real/nhanes_2021_2023_dietary_daily_summary.csv", "data/simulated/neighborhood_health_survey_dietary_daily_summary.csv", "neighborhood dietary daily summary",
  "data/real/nhanes_2021_2023_dietary_person_summary.csv", "data/simulated/neighborhood_health_survey_dietary_person_summary.csv", "neighborhood dietary person summary",
  "data/real/nhanes_2021_2023_analysis.csv", "data/simulated/neighborhood_health_survey_analysis.csv", "joined neighborhood health survey",
  "data/real/prams_2011_selected.csv", "data/simulated/new_parent_wellness_survey.csv", "new-parent wellness subgroup estimates",
  "data/real/wide/prams_state_overall_wide.csv", "data/simulated/new_parent_wellness_state_overall_wide.csv", "new-parent wellness state overall wide",
  "data/real/wide/prams_previous_live_births_wide.csv", "data/simulated/new_parent_previous_births_wide.csv", "new-parent wellness previous births wide",
  "data/real/flu_vaccination_age_time_clean.csv", "data/simulated/respiratory_booster_coverage.csv", "respiratory booster coverage",
  "data/real/wide/flu_vaccination_age_month_wide.csv", "data/simulated/respiratory_booster_age_month_wide.csv", "respiratory booster age-month wide",
  "data/real/wide/flu_vaccination_us_age_season_wide.csv", "data/simulated/respiratory_booster_us_age_season_wide.csv", "respiratory booster national age-season wide",
  "data/real/census_state_race_ethnicity_long.csv", "data/simulated/state_school_enrollment_groups_long.csv", "state school enrollment groups long",
  "data/real/wide/census_state_race_ethnicity_wide.csv", "data/simulated/state_school_enrollment_groups_wide.csv", "state school enrollment groups wide",
  "data/real/state_population_ranks.csv", "data/simulated/state_enrollment_ranks.csv", "state enrollment ranks",
  "data/real/state_race_population_summary.csv", "data/simulated/state_enrollment_group_summary.csv", "state enrollment group summary",
  "data/real/places_county_core_measures_long.csv", "data/simulated/county_wellness_indicators_long.csv", "county wellness indicators long",
  "data/real/places_county_core_measures_wide.csv", "data/simulated/county_wellness_indicators_wide.csv", "county wellness indicators wide",
  "data/real/places_tract_dc_md_va_core_measures_long.csv", "data/simulated/metro_neighborhood_wellness_indicators_long.csv", "metro neighborhood wellness indicators long",
  "data/real/epa_air_quality_county_2025_long.csv", "data/simulated/county_noise_exposure_2025_long.csv", "county noise exposure long",
  "data/real/epa_air_quality_county_2025_wide.csv", "data/simulated/county_noise_exposure_2025_wide.csv", "county noise exposure wide"
)

write_sim_csv(simulated_dataset_crosswalk, "simulated_dataset_crosswalk.csv")

message("Done simulating swappable teaching data files.")
